In [15]:
import pandas as pd
import tabula
import numpy as np

In [2]:
url_l4_01_2021 = "https://www.viaquatro.com.br/Media/ContentPage/Files/56978876e47848ddb11212d2a9f3e53a_entrada-de-passageiros-por-estacao-jan-2020.pdf"
url_l4_02_2021 ="https://www.viaquatro.com.br/Media/ContentPage/Files/97453226e3a24125b139edf10cd2f16e_entrada-de-passageiros-por-estacao-fev-2021-v4.pdf"
url_l4_03_2021 = "https://www.viaquatro.com.br/Media/ContentPage/Files/6388352bbb404615a8677d3b337b326d_entrada-de-passageiros-por-estacao-mar-2021.pdf"
url_l4_04_2021 = "https://www.viaquatro.com.br/Media/ContentPage/Files/4398e4785389485c8f8aefad02533af3_entrada-de-passageiros-por-estacao-abr-2021.pdf"
url_l4_05_2021 = "https://www.viaquatro.com.br/Media/ContentPage/Files/44a1ecb0235e4b838ac8ef762c551690_entrada-de-passageiros-por-estacao.pdf"
url_l4_06_2021 = "https://www.viaquatro.com.br/Media/ContentPage/Files/e295808361a840ddbd4d7ae609601fd6_06-2021-entrada-de-passageiros-por-estacao.pdf"
url_l4_07_2021 = "https://www.viaquatro.com.br/Media/ContentPage/Files/c391a9b179e24d1cba46784565d38055_07-entrada-de-passageiros-por-estacao.pdf"
url_l4_08_2021 = "https://www.viaquatro.com.br/Media/ContentPage/Files/3dfd0754af2641a690fb1cbf6304e48f_08-entrada-de-passageiros-por-estacao.pdf"
url_l4_09_2021 = "https://www.viaquatro.com.br/Media/ContentPage/Files/af4301c245ce48e58f94b771bdd3a0c4_09-entrada-por-estacao.pdf"
url_l4_10_2021 = "https://www.viaquatro.com.br/Media/ContentPage/Files/f5c47a4eea3c47f584f77184d74a6582_entrada-de-passageiros-por-estacao.pdf"
url_l4_11_2021 = "https://www.viaquatro.com.br/Media/ContentPage/Files/d8a39ba536904eb0a685e98e245900fe_entrada-de-passageiros-por-estacao-nov.pdf"
url_l4_12_2021 = "https://www.viaquatro.com.br/Media/ContentPage/Files/5f18966f840a4e3c987da7a89c73bda1_12-demanda-de-passageiros-por-estacao.pdf"

In [3]:
#    Passenger Entry by Station 2021
demanda_estacao_4_01_2021 = tabula.read_pdf(url_l4_01_2021,pages=1)
demanda_estacao_4_01_2021 = demanda_estacao_4_01_2021[0]
demanda_estacao_4_01_2021.columns = ['Station','January']
demanda_estacao_4_01_2021 = demanda_estacao_4_01_2021.drop(0,axis=0)


demanda_estacao_4_02_2021 = tabula.read_pdf(url_l4_02_2021,pages=1)
demanda_estacao_4_02_2021 = demanda_estacao_4_02_2021[0]
demanda_estacao_4_02_2021.columns = ['Station','February']
demanda_estacao_4_02_2021 = demanda_estacao_4_02_2021.drop(0,axis=0)

demanda_estacao_4_2021 = pd.merge(demanda_estacao_4_01_2021, demanda_estacao_4_02_2021, 
                                  how = 'inner', on = 'Station')

demanda_estacao_4_03_2021 = tabula.read_pdf(url_l4_03_2021,pages=1)
demanda_estacao_4_03_2021 = demanda_estacao_4_03_2021[0]
demanda_estacao_4_03_2021.columns = ['Station','March']
demanda_estacao_4_03_2021 = demanda_estacao_4_03_2021.drop(0,axis=0)

demanda_estacao_4_2021 = pd.merge(demanda_estacao_4_2021, demanda_estacao_4_03_2021, 
                                  how = 'inner', on = 'Station')


demanda_estacao_4_04_2021 = tabula.read_pdf(url_l4_04_2021,pages=1)
demanda_estacao_4_04_2021 = demanda_estacao_4_04_2021[0]
demanda_estacao_4_04_2021.columns = ['Station','April']
demanda_estacao_4_04_2021 = demanda_estacao_4_04_2021.drop(0,axis=0)

demanda_estacao_4_2021 = pd.merge(demanda_estacao_4_2021, demanda_estacao_4_04_2021, 
                                  how = 'inner', on = 'Station')

demanda_estacao_4_05_2021 = tabula.read_pdf(url_l4_05_2021,pages=1)
demanda_estacao_4_05_2021 = demanda_estacao_4_05_2021[0]
demanda_estacao_4_05_2021.columns = ['Station','May']
demanda_estacao_4_05_2021 = demanda_estacao_4_05_2021.drop(0,axis=0)

demanda_estacao_4_2021 = pd.merge(demanda_estacao_4_2021, demanda_estacao_4_05_2021, 
                                  how = 'inner', on = 'Station')

demanda_estacao_4_06_2021 = tabula.read_pdf(url_l4_06_2021,pages=1)
demanda_estacao_4_06_2021 = demanda_estacao_4_06_2021[0]
demanda_estacao_4_06_2021.columns = ['Station','June']
demanda_estacao_4_06_2021 = demanda_estacao_4_06_2021.drop(0,axis=0)

demanda_estacao_4_2021 = pd.merge(demanda_estacao_4_2021, demanda_estacao_4_06_2021, 
                                  how = 'inner', on = 'Station')

demanda_estacao_4_07_2021 = tabula.read_pdf(url_l4_07_2021,pages=1)
demanda_estacao_4_07_2021 = demanda_estacao_4_07_2021[0]
demanda_estacao_4_07_2021.columns = ['Station','July']
demanda_estacao_4_07_2021 = demanda_estacao_4_07_2021.drop(0,axis=0)

demanda_estacao_4_2021 = pd.merge(demanda_estacao_4_2021, demanda_estacao_4_07_2021, 
                                  how = 'inner', on = 'Station')

demanda_estacao_4_08_2021 = tabula.read_pdf(url_l4_08_2021,pages=1)
demanda_estacao_4_08_2021 = demanda_estacao_4_08_2021[0]
demanda_estacao_4_08_2021.columns = ['Station','August']
demanda_estacao_4_08_2021 = demanda_estacao_4_08_2021.drop(0,axis=0)

demanda_estacao_4_2021 = pd.merge(demanda_estacao_4_2021, demanda_estacao_4_08_2021, 
                                  how = 'inner', on = 'Station')

demanda_estacao_4_09_2021 = tabula.read_pdf(url_l4_09_2021,pages=1)
demanda_estacao_4_09_2021 = demanda_estacao_4_09_2021[0]
demanda_estacao_4_09_2021.columns = ['Station','September']
demanda_estacao_4_09_2021 = demanda_estacao_4_09_2021.drop(0,axis=0)

demanda_estacao_4_2021 = pd.merge(demanda_estacao_4_2021, demanda_estacao_4_09_2021, 
                                  how = 'inner', on = 'Station')


demanda_estacao_4_10_2021 = tabula.read_pdf(url_l4_10_2021,pages=1)
demanda_estacao_4_10_2021 = demanda_estacao_4_10_2021[0]
demanda_estacao_4_10_2021.columns = ['Station','October']
demanda_estacao_4_10_2021 = demanda_estacao_4_10_2021.drop(0,axis=0)

demanda_estacao_4_2021 = pd.merge(demanda_estacao_4_2021, demanda_estacao_4_10_2021, 
                                  how = 'inner', on = 'Station')

demanda_estacao_4_11_2021 = tabula.read_pdf(url_l4_11_2021,pages=1)
demanda_estacao_4_11_2021 = demanda_estacao_4_11_2021[0]
demanda_estacao_4_11_2021.columns = ['Station','November']
demanda_estacao_4_11_2021 = demanda_estacao_4_11_2021.drop(0,axis=0)

demanda_estacao_4_2021 = pd.merge(demanda_estacao_4_2021, demanda_estacao_4_11_2021, 
                                  how = 'inner', on = 'Station')



demanda_estacao_4_12_2021 = tabula.read_pdf(url_l4_12_2021,pages=1)
demanda_estacao_4_12_2021 = demanda_estacao_4_12_2021[0]
demanda_estacao_4_12_2021.columns = ['Station','December']
demanda_estacao_4_12_2021 = demanda_estacao_4_12_2021.drop(0,axis=0)

demanda_estacao_4_2021 = pd.merge(demanda_estacao_4_2021, demanda_estacao_4_12_2021, 
                                  how = 'inner', on = 'Station')
#demanda_estacao_4_2021 = pd.merge(demanda_estacao_4_01_2021, demanda_estacao_4_02_2021, demanda_estacao_4_03_2021, how = 'inner', on = 'Station')

columns = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November','December']

demanda_estacao_4_2021[columns] = demanda_estacao_4_2021[columns].apply(lambda x: x.str.replace(',', '.').astype('float'))

In [4]:
display(demanda_estacao_4_2021)

,Station,January,February,March,April,May,June,July,August,September,October,November,December
0,SÃ£o Paulo - Morumbi,26.0,27.0,22.0,22.0,25.0,26.0,27.0,30.0,31.0,33.52,35.99,32.80
1,ButantÃ£,22.0,23.0,19.0,18.0,21.0,22.0,23.0,25.0,27.0,28.33,30.12,27.31
2,Pinheiros1,55.0,58.0,47.0,46.0,53.0,55.0,55.0,62.0,67.0,71.08,77.69,70.48
3,Faria Lima,16.0,17.0,13.0,12.0,15.0,16.0,16.0,18.0,19.0,20.61,22.36,19.25
4,Fradique Coutinho,9.0,9.0,7.0,7.0,8.0,9.0,9.0,10.0,11.0,11.44,12.39,10.92
5,Oscar Freire,14.0,15.0,12.0,12.0,14.0,14.0,15.0,16.0,16.0,17.10,18.19,16.28
6,Paulista2,53.0,57.0,45.0,42.0,48.0,50.0,53.0,59.0,63.0,66.49,72.33,64.31
7,HigienÃ³polis - Mackenzie,9.0,10.0,8.0,7.0,9.0,9.0,9.0,11.0,12.0,12.93,14.41,11.71
8,RepÃºblica3,63.0,66.0,52.0,50.0,57.0,61.0,64.0,69.0,73.0,77.11,83.66,77.03
9,Luz4,75.0,78.0,63.0,61.0,74.0,76.0,80.0,86.0,92.0,96.20,102.10,93.54
10,TOTAL,341.0,360.0,288.0,276.0,324.0,336.0,350.0,386.0,409.0,434.81,469.24,423.65

In [5]:
media =[]
for i in demanda_estacao_4_2021.index:
    media.append(demanda_estacao_4_2021.iloc[i,1:].mean())
demanda_estacao_4_2021['Mean'] = media 
demanda_estacao_4_2021['Year'] = '2021'
demanda_estacao_4_2021['Line'] = '4_Yellow'
display(demanda_estacao_4_2021)

,Station,January,February,March,April,May,June,July,August,September,October,November,December,Mean,Year,Line
0,SÃ£o Paulo - Morumbi,26.0,27.0,22.0,22.0,25.0,26.0,27.0,30.0,31.0,33.52,35.99,32.80,28.192500,2021,4_Yellow
1,ButantÃ£,22.0,23.0,19.0,18.0,21.0,22.0,23.0,25.0,27.0,28.33,30.12,27.31,23.813333,2021,4_Yellow
2,Pinheiros1,55.0,58.0,47.0,46.0,53.0,55.0,55.0,62.0,67.0,71.08,77.69,70.48,59.770833,2021,4_Yellow
3,Faria Lima,16.0,17.0,13.0,12.0,15.0,16.0,16.0,18.0,19.0,20.61,22.36,19.25,17.018333,2021,4_Yellow
4,Fradique Coutinho,9.0,9.0,7.0,7.0,8.0,9.0,9.0,10.0,11.0,11.44,12.39,10.92,9.479167,2021,4_Yellow
5,Oscar Freire,14.0,15.0,12.0,12.0,14.0,14.0,15.0,16.0,16.0,17.10,18.19,16.28,14.964167,2021,4_Yellow
6,Paulista2,53.0,57.0,45.0,42.0,48.0,50.0,53.0,59.0,63.0,66.49,72.33,64.31,56.094167,2021,4_Yellow
7,HigienÃ³polis - Mackenzie,9.0,10.0,8.0,7.0,9.0,9.0,9.0,11.0,12.0,12.93,14.41,11.71,10.254167,2021,4_Yellow
8,RepÃºblica3,63.0,66.0,52.0,50.0,57.0,61.0,64.0,69.0,73.0,77.11,83.66,77.03,66.066667,2021,4_Yellow
9,Luz4,75.0,78.0,63.0,61.0,74.0,76.0,80.0,86.0,92.0,96.20,102.10,93.54,81.403333,2021,4_Yellow
10,TOTAL,341.0,360.0,288.0,276.0,324.0,336.0,350.0,386.0,409.0,434.81,469.24,423.65,366.475000,2021,4_Yellow

In [6]:
demanda_estacao_4_2021.to_csv("demanda_estacao_4_2021.csv")

In [7]:
url_l4_01_2022 = "https://www.viaquatro.com.br/Media/ContentPage/Files/98e926e497d44281a4b43621c52c6d2e_demanda-de-passageiros-por-estacao.pdf"
url_l4_02_2022 ="https://www.viaquatro.com.br/Media/ContentPage/Files/5354df61a19e4f8d9fd92b6c1e15b5ed_entrada-de-passageiros-por-estacao.pdf"
url_l4_03_2022 = "https://www.viaquatro.com.br/Media/ContentPage/Files/63c72fa8dad847e98aa94c2be1789490_entrada-de-passageiros-por-estacao.pdf"
url_l4_04_2022 = "https://www.viaquatro.com.br/Media/ContentPage/Files/3c10ed546ed246a297970c19ed9b1cfa_entrada-de-passageiros-por-estacao.pdf"
url_l4_05_2022 = "https://www.viaquatro.com.br/Media/ContentPage/Files/3d009751659c42b8b77ac7ac34db192d_demanda-de-passageiros-por-estacao.pdf"
url_l4_06_2022 = "https://www.viaquatro.com.br/Media/ContentPage/Files/e380f0448e3041a3a1da3ec6993d569f_demanda-de-passageiros-por-estacao.pdf"
url_l4_07_2022 = "https://www.viaquatro.com.br/Media/ContentPage/Files/80e5e13c41234f489b0942ddd5cafdda_demanda-de-passageiros-por-estacao.pdf"
url_l4_08_2022 = "https://www.viaquatro.com.br/Media/ContentPage/Files/bf441a5d366542f9b4b5e72be3ffa6ac_demanda-de-passageiros-por-estacao.pdf"
url_l4_09_2022 = "https://www.viaquatro.com.br/Media/ContentPage/Files/352fc5eeeb8c4135b2a46b136d4f0da7_demanda-de-passageiros-por-estacao.pdf"
url_l4_10_2022 = "https://www.viaquatro.com.br/Media/ContentPage/Files/41581f7b12404766ab812d94b56db84f_demanda-de-passageiros-por-estacao.pdf"
url_l4_11_2022 = "https://www.viaquatro.com.br/Media/ContentPage/Files/831f2c9a12454dadbf630055a49437a6_demanda-de-passageiros-viaquatro-estacoes-novembro-2022.pdf"
url_l4_12_2022 = "https://www.viaquatro.com.br/Media/ContentPage/Files/778b590360a846619546fa740a8c819c_demanda-de-passageiros-vq-estacoes-dezembro-2022.pdf"

In [8]:
#    Passenger Entry by Station 2022
demanda_estacao_4_01_2022 = tabula.read_pdf(url_l4_01_2022,pages=1)
demanda_estacao_4_01_2022 = demanda_estacao_4_01_2022[0]
demanda_estacao_4_01_2022.columns = ['Station','January']
demanda_estacao_4_01_2022 = demanda_estacao_4_01_2022.drop(0,axis=0)


demanda_estacao_4_02_2022 = tabula.read_pdf(url_l4_02_2022,pages=1)
demanda_estacao_4_02_2022 = demanda_estacao_4_02_2022[0]
demanda_estacao_4_02_2022.columns = ['Station','February']
demanda_estacao_4_02_2022 = demanda_estacao_4_02_2022.drop(0,axis=0)

demanda_estacao_4_2022 = pd.merge(demanda_estacao_4_01_2022, demanda_estacao_4_02_2022, 
                                  how = 'inner', on = 'Station')

demanda_estacao_4_03_2022 = tabula.read_pdf(url_l4_03_2022,pages=1)
demanda_estacao_4_03_2022 = demanda_estacao_4_03_2022[0]
demanda_estacao_4_03_2022.columns = ['Station','March']
demanda_estacao_4_03_2022 = demanda_estacao_4_03_2022.drop(0,axis=0)

demanda_estacao_4_2022 = pd.merge(demanda_estacao_4_2022, demanda_estacao_4_03_2022, 
                                  how = 'inner', on = 'Station')


demanda_estacao_4_04_2022 = tabula.read_pdf(url_l4_04_2022,pages=1)
demanda_estacao_4_04_2022 = demanda_estacao_4_04_2022[0]
demanda_estacao_4_04_2022.columns = ['Station','April']
demanda_estacao_4_04_2022 = demanda_estacao_4_04_2022.drop(0,axis=0)

demanda_estacao_4_2022 = pd.merge(demanda_estacao_4_2022, demanda_estacao_4_04_2022, 
                                  how = 'inner', on = 'Station')

demanda_estacao_4_05_2022 = tabula.read_pdf(url_l4_05_2022,pages=1)
demanda_estacao_4_05_2022 = demanda_estacao_4_05_2022[0]
demanda_estacao_4_05_2022.columns = ['Station','May']
demanda_estacao_4_05_2022 = demanda_estacao_4_05_2022.drop(0,axis=0)

demanda_estacao_4_2022 = pd.merge(demanda_estacao_4_2022, demanda_estacao_4_05_2022, 
                                  how = 'inner', on = 'Station')

demanda_estacao_4_06_2022 = tabula.read_pdf(url_l4_06_2022,pages=1)
demanda_estacao_4_06_2022 = demanda_estacao_4_06_2022[0]
demanda_estacao_4_06_2022.columns = ['Station','June']
demanda_estacao_4_06_2022 = demanda_estacao_4_06_2022.drop(0,axis=0)

demanda_estacao_4_2022 = pd.merge(demanda_estacao_4_2022, demanda_estacao_4_06_2022, 
                                  how = 'inner', on = 'Station')

demanda_estacao_4_07_2022 = tabula.read_pdf(url_l4_07_2022,pages=1)
demanda_estacao_4_07_2022 = demanda_estacao_4_07_2022[0]
demanda_estacao_4_07_2022.columns = ['Station','July']
demanda_estacao_4_07_2022 = demanda_estacao_4_07_2022.drop(0,axis=0)

demanda_estacao_4_2022 = pd.merge(demanda_estacao_4_2022, demanda_estacao_4_07_2022, 
                                  how = 'inner', on = 'Station')

demanda_estacao_4_08_2022 = tabula.read_pdf(url_l4_08_2022,pages=1)
demanda_estacao_4_08_2022 = demanda_estacao_4_08_2022[0]
demanda_estacao_4_08_2022.columns = ['Station','August']
demanda_estacao_4_08_2022 = demanda_estacao_4_08_2022.drop(0,axis=0)

demanda_estacao_4_2022 = pd.merge(demanda_estacao_4_2022, demanda_estacao_4_08_2022, 
                                  how = 'inner', on = 'Station')

demanda_estacao_4_09_2022 = tabula.read_pdf(url_l4_09_2022,pages=1)
demanda_estacao_4_09_2022 = demanda_estacao_4_09_2022[0]
demanda_estacao_4_09_2022.columns = ['Station','September']
demanda_estacao_4_09_2022 = demanda_estacao_4_09_2022.drop(0,axis=0)

demanda_estacao_4_2022 = pd.merge(demanda_estacao_4_2022, demanda_estacao_4_09_2022, 
                                  how = 'inner', on = 'Station')


demanda_estacao_4_10_2022 = tabula.read_pdf(url_l4_10_2022,pages=1)
demanda_estacao_4_10_2022 = demanda_estacao_4_10_2022[0]
demanda_estacao_4_10_2022.columns = ['Station','October']
demanda_estacao_4_10_2022 = demanda_estacao_4_10_2022.drop(0,axis=0)

demanda_estacao_4_2022 = pd.merge(demanda_estacao_4_2022, demanda_estacao_4_10_2022, 
                                  how = 'inner', on = 'Station')

demanda_estacao_4_11_2022 = tabula.read_pdf(url_l4_11_2022,pages=1)
demanda_estacao_4_11_2022 = demanda_estacao_4_11_2022[0]
demanda_estacao_4_11_2022.columns = ['Station','November']
demanda_estacao_4_11_2022 = demanda_estacao_4_11_2022.drop(0,axis=0)

demanda_estacao_4_2022 = pd.merge(demanda_estacao_4_2022, demanda_estacao_4_11_2022, 
                                  how = 'inner', on = 'Station')



demanda_estacao_4_12_2022 = tabula.read_pdf(url_l4_12_2022,pages=1)
demanda_estacao_4_12_2022 = demanda_estacao_4_12_2022[0]
demanda_estacao_4_12_2022.columns = ['Station','December']
demanda_estacao_4_12_2022 = demanda_estacao_4_12_2022.drop(0,axis=0)

demanda_estacao_4_2022 = pd.merge(demanda_estacao_4_2022, demanda_estacao_4_12_2022, 
                                  how = 'inner', on = 'Station')
#demanda_estacao_4_2021 = pd.merge(demanda_estacao_4_01_2021, demanda_estacao_4_02_2021, demanda_estacao_4_03_2021, how = 'inner', on = 'Station')

columns = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November','December']

demanda_estacao_4_2022[columns] = demanda_estacao_4_2022[columns].apply(lambda x: x.str.replace(',', '.').astype('float'))

In [9]:
display(demanda_estacao_4_2022)

,Station,January,February,March,April,May,June,July,August,September,October,November,December
0,SÃ£o Paulo - Morumbi,28.67,34.83,39.90,41.25,31.67,22.30,21.10,22.60,22.29,22.26,21.69,19.28
1,ButantÃ£,24.31,28.94,35.45,38.81,38.90,34.39,31.48,34.80,36.29,37.06,35.77,29.87
2,Pinheiros1,62.94,72.94,82.60,87.17,88.74,87.80,88.44,93.98,97.37,99.58,98.30,88.83
3,Faria Lima,18.26,22.50,25.40,27.56,28.84,30.33,30.30,32.48,32.59,32.94,32.24,29.14
4,Fradique Coutinho,9.88,11.98,13.27,14.06,14.54,15.21,15.28,16.09,16.34,16.61,16.61,14.85
5,Oscar Freire,14.79,17.68,18.90,19.59,20.12,20.73,20.68,21.81,21.51,22.12,22.13,20.40
6,Paulista2,57.80,69.89,84.41,89.55,92.59,87.61,83.57,95.27,99.42,100.28,96.55,83.74
7,HigienÃ³polis - Mackenzie,10.60,13.87,19.03,22.21,23.68,18.50,15.28,25.05,25.73,24.11,23.68,15.96
8,RepÃºblica3,68.47,79.68,93.18,95.65,96.73,94.34,93.31,98.97,102.74,104.29,102.12,92.74
9,Luz4,86.07,98.16,106.27,114.17,117.02,113.85,115.08,121.01,126.39,127.55,125.18,114.43
10,TOTAL,381.81,450.46,518.39,550.01,569.18,559.54,548.41,599.54,619.43,626.43,613.22,544.99

In [10]:
media =[]
for i in demanda_estacao_4_2022.index:
    media.append(demanda_estacao_4_2022.iloc[i,1:].mean())
demanda_estacao_4_2022['Mean'] = media 
demanda_estacao_4_2022['Year'] = '2022'
demanda_estacao_4_2022['Line'] = '4_Yellow'
display(demanda_estacao_4_2022)

,Station,January,February,March,April,May,June,July,August,September,October,November,December,Mean,Year,Line
0,SÃ£o Paulo - Morumbi,28.67,34.83,39.90,41.25,31.67,22.30,21.10,22.60,22.29,22.26,21.69,19.28,27.320000,2022,4_Yellow
1,ButantÃ£,24.31,28.94,35.45,38.81,38.90,34.39,31.48,34.80,36.29,37.06,35.77,29.87,33.839167,2022,4_Yellow
2,Pinheiros1,62.94,72.94,82.60,87.17,88.74,87.80,88.44,93.98,97.37,99.58,98.30,88.83,87.390833,2022,4_Yellow
3,Faria Lima,18.26,22.50,25.40,27.56,28.84,30.33,30.30,32.48,32.59,32.94,32.24,29.14,28.548333,2022,4_Yellow
4,Fradique Coutinho,9.88,11.98,13.27,14.06,14.54,15.21,15.28,16.09,16.34,16.61,16.61,14.85,14.560000,2022,4_Yellow
5,Oscar Freire,14.79,17.68,18.90,19.59,20.12,20.73,20.68,21.81,21.51,22.12,22.13,20.40,20.038333,2022,4_Yellow
6,Paulista2,57.80,69.89,84.41,89.55,92.59,87.61,83.57,95.27,99.42,100.28,96.55,83.74,86.723333,2022,4_Yellow
7,HigienÃ³polis - Mackenzie,10.60,13.87,19.03,22.21,23.68,18.50,15.28,25.05,25.73,24.11,23.68,15.96,19.808333,2022,4_Yellow
8,RepÃºblica3,68.47,79.68,93.18,95.65,96.73,94.34,93.31,98.97,102.74,104.29,102.12,92.74,93.518333,2022,4_Yellow
9,Luz4,86.07,98.16,106.27,114.17,117.02,113.85,115.08,121.01,126.39,127.55,125.18,114.43,113.765000,2022,4_Yellow
10,TOTAL,381.81,450.46,518.39,550.01,569.18,559.54,548.41,599.54,619.43,626.43,613.22,544.99,548.450833,2022,4_Yellow

In [11]:
demanda_estacao_4_2022.to_csv("demanda_estacao_4_2022.csv")

In [13]:
url_l4_01_2023 = "https://www.viaquatro.com.br/Media/ContentPage/Files/ccdbf3b80ac549618e27eee4b5ad6f7c_demanda-de-passageiros-por-estacao.pdf"
url_l4_02_2023 ="https://www.viaquatro.com.br/Media/ContentPage/Files/e30e230c70794c7284e9303f838b551b_demanda-de-passageiros-por-estacao.pdf"
url_l4_03_2023 = "https://www.viaquatro.com.br/Media/ContentPage/Files/4d5ba4a89fb347eca540a0f9fb901412_demanda-de-passageiros-por-estacao.pdf"
url_l4_04_2023 = "https://www.viaquatro.com.br/Media/ContentPage/Files/e1cadba2fde64535ac253dd5841492c9_demanda-de-passageiros-por-estacao.pdf"
url_l4_05_2023 = ""
url_l4_06_2023 = ""
url_l4_07_2023 = ""
url_l4_08_2023 = ""
url_l4_09_2023 = ""
url_l4_10_2023 = ""
url_l4_11_2023 = ""
url_l4_12_2023 = ""

In [22]:
#    Passenger Entry by Station 2023
demanda_estacao_4_01_2023 = tabula.read_pdf(url_l4_01_2023,pages=1)
demanda_estacao_4_01_2023 = demanda_estacao_4_01_2023[0]
demanda_estacao_4_01_2023.columns = ['Station','January']
demanda_estacao_4_01_2023 = demanda_estacao_4_01_2023.drop(0,axis=0)


demanda_estacao_4_02_2023 = tabula.read_pdf(url_l4_02_2023,pages=1)
demanda_estacao_4_02_2023 = demanda_estacao_4_02_2023[0]
demanda_estacao_4_02_2023.columns = ['Station','February']
demanda_estacao_4_02_2023 = demanda_estacao_4_02_2023.drop(0,axis=0)

demanda_estacao_4_2023 = pd.merge(demanda_estacao_4_01_2023, demanda_estacao_4_02_2023, 
                                  how = 'inner', on = 'Station')

demanda_estacao_4_03_2023 = tabula.read_pdf(url_l4_03_2023,pages=1)
demanda_estacao_4_03_2023 = demanda_estacao_4_03_2023[0]
demanda_estacao_4_03_2023.columns = ['Station','March']
demanda_estacao_4_03_2023 = demanda_estacao_4_03_2023.drop(0,axis=0)

demanda_estacao_4_2023 = pd.merge(demanda_estacao_4_2023, demanda_estacao_4_03_2023, 
                                  how = 'inner', on = 'Station')


demanda_estacao_4_04_2023 = tabula.read_pdf(url_l4_04_2023,pages=1)
demanda_estacao_4_04_2023 = demanda_estacao_4_04_2023[0]
demanda_estacao_4_04_2023.columns = ['Station','April']
demanda_estacao_4_04_2023 = demanda_estacao_4_04_2023.drop(0,axis=0)

demanda_estacao_4_2023 = pd.merge(demanda_estacao_4_2023, demanda_estacao_4_04_2023, 
                                  how = 'inner', on = 'Station')

columns = ['January', 'February', 'March', 'April']

demanda_estacao_4_2023[columns] = demanda_estacao_4_2023[columns].apply(lambda x: x.str.replace(',', '.').astype('float'))

demanda_estacao_4_2023[['May', 'June', 'July', 'August', 'September', 'October', 'November','December']] = np.nan





display(demanda_estacao_4_2023)

,Station,January,February,March,April,May,June,July,August,September,October,November,December
0,Vila SÃ´nia,34.54,38.15,42.21,43.98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,SÃ£o Paulo - Morumbi,18.26,20.17,24.15,23.37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ButantÃ£,27.17,29.85,36.43,38.63,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Pinheiros1,87.15,91.47,103.42,104.83,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Faria Lima,28.65,30.31,33.71,34.54,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Fradique Coutinho,14.56,16.09,17.08,17.18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Oscar Freire,19.87,20.93,23.50,24.02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Paulista2,82.55,92.87,101.89,105.55,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,HigienÃ³polis - Mackenzie,14.58,23.50,27.51,27.48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,RepÃºblica3,90.08,96.67,102.68,106.20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Luz4,113.58,120.29,136.49,135.69,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,TOTAL,530.98,580.30,649.07,661.45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
media =[]
for i in demanda_estacao_4_2023.index:
    media.append(demanda_estacao_4_2023.iloc[i,1:5].mean())
demanda_estacao_4_2023['Mean'] = media 
demanda_estacao_4_2023['Year'] = '2023'
demanda_estacao_4_2023['Line'] = '4_Yellow'
display(demanda_estacao_4_2023)

,Station,January,February,March,April,May,June,July,August,September,October,November,December,Mean,Year,Line
0,Vila SÃ´nia,34.54,38.15,42.21,43.98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39.7200,2023,4_Yellow
1,SÃ£o Paulo - Morumbi,18.26,20.17,24.15,23.37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.4875,2023,4_Yellow
2,ButantÃ£,27.17,29.85,36.43,38.63,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.0200,2023,4_Yellow
3,Pinheiros1,87.15,91.47,103.42,104.83,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,96.7175,2023,4_Yellow
4,Faria Lima,28.65,30.31,33.71,34.54,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.8025,2023,4_Yellow
5,Fradique Coutinho,14.56,16.09,17.08,17.18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.2275,2023,4_Yellow
6,Oscar Freire,19.87,20.93,23.50,24.02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.0800,2023,4_Yellow
7,Paulista2,82.55,92.87,101.89,105.55,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,95.7150,2023,4_Yellow
8,HigienÃ³polis - Mackenzie,14.58,23.50,27.51,27.48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.2675,2023,4_Yellow
9,RepÃºblica3,90.08,96.67,102.68,106.20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98.9075,2023,4_Yellow
10,Luz4,113.58,120.29,136.49,135.69,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,126.5125,2023,4_Yellow
11,TOTAL,530.98,580.30,649.07,661.45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,605.4500,2023,4_Yellow

In [24]:
demanda_estacao_4_2023.to_csv("demanda_estacao_4_2023.csv")